#!/bin/bash
# Fetch Amazon search images for all perfumes without images
# Outputs JSON-ready mapping

OUTFILE="$(dirname "$0")/amazon-image-map.json"
echo "{" > "$OUTFILE"

get_img() {
  local NAME="$1"
  local BRAND="$2"
  local QUERY="${BRAND}+${NAME}+perfume"
  IMG=$(curl -sL "https://www.amazon.com/s?k=${QUERY// /+}&i=beauty" \
    -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" \
    --compressed 2>&1 | grep -oE 'https://m\.media-amazon\.com/images/I/[A-Za-z0-9+_-]+L\._AC_UL[0-9]+_\.' | head -1 | sed 's/\._AC_UL[0-9]*_\./._SL500_.jpg/')
  if [ -n "$IMG" ]; then
    echo "  \"$NAME\": \"$IMG\"," >> "$OUTFILE"
    echo "OK: $NAME ($BRAND)"
  else
    echo "SKIP: $NAME ($BRAND)"
  fi
  sleep 2
}

# All 104 perfumes without images
get_img "Khamrah" "Lattafa"
get_img "Asad" "Lattafa"
get_img "Yara" "Lattafa"
get_img "Oud for Glory" "Lattafa"
get_img "Raghba" "Lattafa"
get_img "Ana Abiyedh" "Lattafa"
get_img "Qaed Al Fursan" "Lattafa"
get_img "Bade'e Al Oud Amethyst" "Lattafa"
get_img "9PM" "Afnan"
get_img "Supremacy Silver" "Afnan"
get_img "Turathi Blue" "Afnan"
get_img "Club de Nuit Intense Man" "Armaf"
get_img "Club de Nuit Intense Woman" "Armaf"
get_img "Sillage" "Armaf"
get_img "Aventus" "Creed"
get_img "Green Irish Tweed" "Creed"
get_img "Silver Mountain Water" "Creed"
get_img "Viking" "Creed"
get_img "Baccarat Rouge 540" "MFK"
get_img "Grand Soir" "MFK"
get_img "Oud Silk Mood" "MFK"
get_img "Gentle Fluidity Gold" "MFK"
get_img "Petit Matin" "MFK"
get_img "Aqua Universalis" "MFK"
get_img "Oud Wood" "Tom Ford"
get_img "Tobacco Vanilla" "Tom Ford"
get_img "Lost Cherry" "Tom Ford"
get_img "Bitter Peach" "Tom Ford"
get_img "Noir de Noir" "Tom Ford"
get_img "Black Orchid" "Tom Ford"
get_img "Sauvage" "Dior"
get_img "Miss Dior" "Dior"
get_img "J'adore" "Dior"
get_img "Fahrenheit" "Dior"
get_img "No. 5" "Chanel"
get_img "Bleu de Chanel" "Chanel"
get_img "Coco Mademoiselle" "Chanel"
get_img "Allure Homme Sport" "Chanel"
get_img "Eros" "Versace"
get_img "Dylan Blue" "Versace"
get_img "La Nuit de l'Homme" "YSL"
get_img "Libre" "YSL"
get_img "Acqua di Gio" "Giorgio Armani"
get_img "Si" "Giorgio Armani"
get_img "Armani Code" "Giorgio Armani"
get_img "The One" "Dolce Gabbana"
get_img "Light Blue" "Dolce Gabbana"
get_img "Le Male" "Jean Paul Gaultier"
get_img "Le Male Le Parfum" "Jean Paul Gaultier"
get_img "Shalimar" "Guerlain"
get_img "L'Homme Ideal" "Guerlain"
get_img "Layton" "Parfums de Marly"
get_img "Pegasus" "Parfums de Marly"
get_img "Sedley" "Parfums de Marly"
get_img "Delina" "Parfums de Marly"
get_img "Oud for Greatness" "Initio"
get_img "Side Effect" "Initio"
get_img "Musk Therapy" "Initio"
get_img "Naxos" "Xerjoff"
get_img "Erba Pura" "Xerjoff"
get_img "Alexandria II" "Xerjoff"
get_img "Love Don't Be Shy" "Kilian"
get_img "Good Girl Gone Bad" "Kilian"
get_img "Intense Cafe" "Montale"
get_img "Chocolate Greedy" "Montale"
get_img "Cedrat Boise" "Mancera"
get_img "Instant Crush" "Mancera"
get_img "Red Tobacco" "Mancera"
get_img "Hacivat" "Nishane"
get_img "Ani" "Nishane"
get_img "Hundred Silent Ways" "Nishane"
get_img "Gypsy Water" "Byredo"
get_img "Bal d'Afrique" "Byredo"
get_img "Mojave Ghost" "Byredo"
get_img "Santal 33" "Le Labo"
get_img "Rose 31" "Le Labo"
get_img "Another 13" "Le Labo"
get_img "Jazz Club" "Maison Margiela"
get_img "By the Fireplace" "Maison Margiela"
get_img "Whispers in the Library" "Maison Margiela"
get_img "Terre d'Hermes" "Hermes"
get_img "Un Jardin sur le Nil" "Hermes"
get_img "Interlude Man" "Amouage"
get_img "Reflection Man" "Amouage"
get_img "Jubilation XXV" "Amouage"
get_img "Amber Oud Gold Edition" "Al Haramain"
get_img "Amber Oud Rouge" "Al Haramain"
get_img "L'Aventure" "Al Haramain"
get_img "La Yuqawam" "Rasasi"
get_img "Hawas" "Rasasi"
get_img "Shaghaf Oud" "Swiss Arabian"
get_img "Kashkha" "Swiss Arabian"
get_img "Shaheen" "Swiss Arabian"
get_img "Colonia" "Acqua di Parma"
get_img "Oud & Spice" "Acqua di Parma"
get_img "Halfeti" "Penhaligon"
get_img "Endymion" "Penhaligon"
get_img "Kirke" "Tiziana Terenzi"
get_img "Orion" "Tiziana Terenzi"
get_img "Heritage" "Nabeel"
get_img "Resala" "Arabian Oud"
get_img "Intense Oud" "Arabian Oud"
get_img "Midnight Oud" "Ard Al Zaafaran"
get_img "Noya Oud is My Love" "Zimaya"

# Close JSON
echo '  "_end": null' >> "$OUTFILE"
echo "}" >> "$OUTFILE"

echo "Done! $(grep -c 'media-amazon' "$OUTFILE") images found"
